### ISSUE TITLE
Delete branch by name (instead of id)

### ISSUE THREAD

**Issue by nicksrandall** [neondatabase/delete-branch-action#1]
It would be great if I could delete the branch by the name that I gave it (rather than trying to figure out what the id was that auto generated).

**Comment by raoufchebri** [comment]
Hi @nicksrandall, you can find the action to delete a branch by name here: https://github.com/neondatabase/delete-branch-by-name-action.

Just so you know, this Action won't work if the branch_name doesn't exist or if the branch has children.

```
name: Delete Neon Branch with GitHub Actions Demo
run-name: Delete a Neon Branch by name 🚀
on: [push]
jobs:
  delete-neon-branch-by-name:
    uses: neondatabase/delete-branch-by-name-action.yml@beta
    with:
      project_id: YOUR_PROJECT_ID
      branch_name: YOUR_BRANCH_NAME
      api_key: {{ secrets.NEON_API_KEY }}
```

Let me know if this works for you.
