### ISSUE TITLE
Branch Name not getting picked up

### ISSUE THREAD

**Issue by achadee** [neondatabase/delete-branch-action#12]
Hey guys, you have a small bug in your if statement here

https://github.com/neondatabase/delete-branch-action/blob/main/action.yaml#L32

should be `branch_id`

I tried to open a PR, but I think your permissions dont allow for contributions

**Comment by achadee** [comment]
For anyone else experiencing this issue you can get around it by referencing both a branch and branch_id

```
      - name: "Cleanup Neon Testing"
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}}
          branch_id: ${{ github.event.pull_request.head.ref }}-cypress-tests
          branch: ${{ github.event.pull_request.head.ref }}-cypress-tests
          api_key: ${{ secrets.NEON_API_KEY }}
```
