### ISSUE TITLE
Ability to pass in a list of branch Ids to delete

### ISSUE THREAD

**Issue by angelinashepherd** [neondatabase/delete-branch-action#19]
it would be great if we could also pass in an array of branches to delete, instead of just 1

## Steps to reproduce
perhaps something like
```
name: Delete Neon Branch with GitHub Actions Demo
run-name: Delete a Neon Branch 🚀
on: [push]
jobs:
  delete-neon-branch:
    steps:
      uses: neondatabase/delete-branch-action@v3
      with:
        project_id: rapid-haze-373089
        branch: [br-long-forest-224191]
        api_key: {{ secrets.NEON_API_KEY }}
```
