### ISSUE TITLE
Action throws an authorization error

### ISSUE THREAD

**Issue by nishad-playground** [neondatabase/delete-branch-action#24]
## Steps to reproduce
Using action as described in Readme
```
name: Delete Neon Branch with GitHub Actions Demo
run-name: Delete a Neon Branch 🚀
on: [push]
jobs:
  delete-neon-branch:
    steps:
      uses: neondatabase/delete-branch-action@v3
      with:
        project_id: rapid-haze-373089
        branch: br-long-forest-224191
        api_key: ${{ secrets.NEON_API_KEY }}
```

## Expected result
Deleting branch without producing an error

## Actual result
ERROR: The request could not be authorized due to an internal error

## Environment
Linux X64 github-hosted

## Logs, links

<img width="862" alt="Image" src="https://github.com/user-attachments/assets/46792b40-40d9-4c5d-8c35-e5b5ccd29c69" />

- It narrow downs to the issue with using v2 when installing neonctl `npm i -g neonctl@v2`. If I changed it to latest, it works fine

```
npm i -g neonctl@latest
```

**Comment by luist18** [comment]
Hi @nishad-playground, do you mind sharing the project id?

**Comment by nishad-playground** [comment]
> Hi [@nishad-playground](https://github.com/nishad-playground), do you mind sharing the project id?

hello @luist18 this is the project id I used: `flat-art-32703613`

**Comment by asterikx** [comment]
@luist18 I'm also experiencing the exact same error. Is there already a solution?

**Comment by nishad-playground** [comment]
> @luist18 I'm also experiencing the exact same error. Is there already a solution?

I was able to resolve it by making sure that the action step does have access to api key env.

**Comment by asterikx** [comment]
@nishad-playground thank you! Unfortunately, it doesn't solve the issue in my case. I could confirm that the API key is properly provided by echoing it before the `neondatabase/delete-branch-action`. My project ID is `plain-brook-93209156`.

**Comment by nishad-playground** [comment]
> @nishad-playground thank you! Unfortunately, it doesn't solve the issue in my case. I could confirm that the API key is properly provided by echoing it before the `neondatabase/delete-branch-action`. My project ID is `plain-brook-93209156`.

Okay alternatively what I did is forked the repo and used `npm i -g neonctl@latest` instead of `npm i -g neonctl@v2`

**Comment by asterikx** [comment]
Thanks! I ended up directly using `neonctl` in my workflow. Works just fine!

```
name: Clean-up PR

on:
  pull_request:
    types: [closed]

jobs:
  delete-pr:
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2

      - name: Delete Neon Branch
        run: bunx neonctl branches delete preview/pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }} --project-id ${{ vars.NEON_PROJECT_ID }}
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
```
